---
target_user: gdario

# Debian Source Config
debian_mirror: "deb.debian.org"
debian_release: "testing"

# Package Categories
core_packages:
  - ripgrep
  - git
  - curl
  - ssh
  - vim
  - build-essential
  - unzip

programming_languages:
  rust: stable

user_packages:
  - bat
  - glow
  - jq
  - kubectl
  - kubectx
  - libatomic1 # Gemini cli dependency
  - make
  - sqlite3
  - tree
  - tree-sitter-cli
  - wl-clipboard
