---
- name: Required presetup (packages, checks, secrets...)
  ansible.builtin.include_tasks: subtasks/presetup.yml

- name: Install Toolchains and Languages
  ansible.builtin.include_tasks: subtasks/toolchains.yml

- name: Install nvim
  ansible.builtin.include_tasks: subtasks/nvim.yml

- name: Install AI Tools
  ansible.builtin.include_tasks: subtasks/ai_tools.yml

- name: Configure Shell (Nushell, Starship, Secrets)
  ansible.builtin.include_tasks: subtasks/shell_configuration.yml
