---
- name: Provision Workstations
  hosts: workstations
  become: true
  roles:
    - common
    - users
    - docker
    - { role: programming, tags: ['programming', 'workstation'] }
    - { role: workstation, tags: ['workstation'] }
